// GENERATED by research/typing-movements/scripts/export_movements.py — do not edit.
// Source: outputs/candidates/*.csv at commit 34fc6d5 (RES-03); v1 cut per docs/04-movement-vocabulary-checkpoint.md.
// Provisional until learner data (DEC-16). Regenerate with `make export` in research/typing-movements.
import type { Chunk, TechnicalTransition } from './types';

export const MOVEMENT_VOCABULARY_VERSION = '1.0';

/** The 11 same-finger targets that get isolated practice in v1 (scaffold C3). */
export const TECHNICAL_TRANSITIONS: readonly TechnicalTransition[] = [
  { bigram: 'ed', minShare: 0.00703, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'de', minShare: 0.00439, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'ce', minShare: 0.00354, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_hand_different_fingers' }, sameFingerTravel: 2.14 },
  { bigram: 'ec', minShare: 0.00243, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_hand_different_fingers' }, sameFingerTravel: 2.14 },
  { bigram: 'tr', minShare: 0.00253, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.00 },
  { bigram: 'un', minShare: 0.00330, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.02 },
  { bigram: 'lo', minShare: 0.00387, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'ol', minShare: 0.00274, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'rt', minShare: 0.00234, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.00 },
  { bigram: 'mu', minShare: 0.00100, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.14 },
  { bigram: 'um', minShare: 0.00080, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.14 },
];

/** Common chunks practised only inside words in v1 (scaffold C4). */
export const CHUNKS: readonly Chunk[] = [
  { ngram: 'ing', minShare: 0.00726, stability: 'universal', features: ['double_row_change'] },
  { ngram: 'ion', minShare: 0.00274, stability: 'universal', features: ['redirect'] },
  { ngram: 'tion', minShare: 0.00338, stability: 'two-corpus', features: ['redirect'] },
  { ngram: 'nce', minShare: 0.00167, stability: 'universal', features: ['contains_same_finger'] },
  { ngram: 'ted', minShare: 0.00146, stability: 'universal', features: ['contains_same_finger'] },
];

/** Everyday carrier words per target, short carriers first (research practice-word set). */
export const PRACTICE_WORDS: Readonly<Record<string, readonly string[]>> = {
  ed: ['bed', 'need', 'used', 'asked', 'tried', 'wanted', 'called', 'killed', 'married', 'started', 'happened', 'supposed'],
  de: ['made', 'dead', 'idea', 'deal', 'dear', 'side', 'under', 'death', 'inside', 'outside', 'wonderful', 'understand'],
  ce: ['nice', 'once', 'face', 'place', 'since', 'dance', 'piece', 'chance', 'police', 'office', 'except', 'certainly'],
  ec: ['check', 'piece', 'second', 'become', 'secret', 'expect', 'because', 'perfect', 'special', 'decided', 'security', 'appreciate'],
  tr: ['try', 'true', 'truth', 'tried', 'trust', 'train', 'trying', 'street', 'trouble', 'country', 'control', 'straight'],
  un: ['run', 'fun', 'gun', 'found', 'until', 'under', 'young', 'funny', 'around', 'country', 'running', 'understand'],
  lo: ['lot', 'look', 'love', 'long', 'lost', 'lose', 'looks', 'alone', 'close', 'blood', 'along', 'looking'],
  ol: ['old', 'told', 'hold', 'cool', 'cold', 'fool', 'whole', 'school', 'police', 'follow', 'control', 'absolutely'],
  rt: ['part', 'hurt', 'sort', 'start', 'heart', 'party', 'worth', 'court', 'report', 'started', 'important', 'certainly'],
  mu: ['mud', 'much', 'must', 'music', 'murder', 'museum', 'muscle', 'murders', 'musical', 'murdered', 'murderer', 'community'],
  um: ['jump', 'dumb', 'dump', 'human', 'number', 'summer', 'assume', 'jumped', 'museum', 'dumped', 'numbers', 'circumstances'],
  ing: ['going', 'thing', 'doing', 'being', 'things', 'coming', 'nothing', 'talking', 'getting', 'anything', 'something', 'everything'],
  ion: ['action', 'million', 'station', 'mention', 'question', 'position', 'decision', 'questions', 'attention', 'situation', 'information', 'relationship'],
  tion: ['action', 'station', 'mention', 'question', 'position', 'questions', 'attention', 'situation', 'operation', 'information', 'relationship', 'conversation'],
  nce: ['once', 'since', 'dance', 'chance', 'science', 'chances', 'evidence', 'princess', 'concerned', 'insurance', 'difference', 'experience'],
  ted: ['hated', 'wanted', 'waited', 'started', 'excited', 'invited', 'treated', 'arrested', 'expected', 'committed', 'interested', 'complicated'],
};
