// GENERATED by research/typing-movements/scripts/export_movements.py — do not edit.
// Source: outputs/candidates/*.csv and outputs/tables/bigrams_cross_corpus.csv at commit 34fc6d5 (RES-01/RES-03); v1 cut per docs/04-movement-vocabulary-checkpoint.md.
// Provisional until learner data (DEC-16). Regenerate with `make export` in research/typing-movements.
import type { Chunk, TechnicalTransition } from './types';

export const MOVEMENT_VOCABULARY_VERSION = '1.1';

/** The 11 same-finger targets that get isolated practice in v1 (scaffold C3). */
export const TECHNICAL_TRANSITIONS: readonly TechnicalTransition[] = [
  { bigram: 'ed', minShare: 0.00703, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'de', minShare: 0.00439, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'ce', minShare: 0.00354, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_hand_different_fingers' }, sameFingerTravel: 2.14 },
  { bigram: 'ec', minShare: 0.00243, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_hand_different_fingers' }, sameFingerTravel: 2.14 },
  { bigram: 'tr', minShare: 0.00253, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.00 },
  { bigram: 'un', minShare: 0.00330, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.02 },
  { bigram: 'lo', minShare: 0.00387, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'ol', minShare: 0.00274, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.03 },
  { bigram: 'rt', minShare: 0.00234, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 1.00 },
  { bigram: 'mu', minShare: 0.00100, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.14 },
  { bigram: 'um', minShare: 0.00080, stability: 'universal', classByMethod: { 'traditional@1.0': 'same_finger_different_key', 'relaxed-qwerty@1.0': 'same_finger_different_key' }, sameFingerTravel: 2.14 },
];

/** Common chunks practised only inside words in v1 (scaffold C4). */
export const CHUNKS: readonly Chunk[] = [
  { ngram: 'ing', minShare: 0.00726, stability: 'universal', features: ['double_row_change'] },
  { ngram: 'ion', minShare: 0.00274, stability: 'universal', features: ['redirect'] },
  { ngram: 'tion', minShare: 0.00338, stability: 'two-corpus', features: ['redirect'] },
  { ngram: 'nce', minShare: 0.00167, stability: 'universal', features: ['contains_same_finger'] },
  { ngram: 'ted', minShare: 0.00146, stability: 'universal', features: ['contains_same_finger'] },
];

/** Everyday carrier words per target, short carriers first (research practice-word set). */
export const PRACTICE_WORDS: Readonly<Record<string, readonly string[]>> = {
  ed: ['bed', 'need', 'used', 'asked', 'tried', 'wanted', 'called', 'killed', 'married', 'started', 'happened', 'supposed'],
  de: ['made', 'dead', 'idea', 'deal', 'dear', 'side', 'under', 'death', 'inside', 'outside', 'wonderful', 'understand'],
  ce: ['nice', 'once', 'face', 'place', 'since', 'dance', 'piece', 'chance', 'police', 'office', 'except', 'certainly'],
  ec: ['check', 'piece', 'second', 'become', 'secret', 'expect', 'because', 'perfect', 'special', 'decided', 'security', 'appreciate'],
  tr: ['try', 'true', 'truth', 'tried', 'trust', 'train', 'trying', 'street', 'trouble', 'country', 'control', 'straight'],
  un: ['run', 'fun', 'gun', 'found', 'until', 'under', 'young', 'funny', 'around', 'country', 'running', 'understand'],
  lo: ['lot', 'look', 'love', 'long', 'lost', 'lose', 'looks', 'alone', 'close', 'blood', 'along', 'looking'],
  ol: ['old', 'told', 'hold', 'cool', 'cold', 'fool', 'whole', 'school', 'police', 'follow', 'control', 'absolutely'],
  rt: ['part', 'hurt', 'sort', 'start', 'heart', 'party', 'worth', 'court', 'report', 'started', 'important', 'certainly'],
  mu: ['mud', 'much', 'must', 'music', 'murder', 'museum', 'muscle', 'murders', 'musical', 'murdered', 'murderer', 'community'],
  um: ['jump', 'dumb', 'dump', 'human', 'number', 'summer', 'assume', 'jumped', 'museum', 'dumped', 'numbers', 'circumstances'],
  ing: ['going', 'thing', 'doing', 'being', 'things', 'coming', 'nothing', 'talking', 'getting', 'anything', 'something', 'everything'],
  ion: ['action', 'million', 'station', 'mention', 'question', 'position', 'decision', 'questions', 'attention', 'situation', 'information', 'relationship'],
  tion: ['action', 'station', 'mention', 'question', 'position', 'questions', 'attention', 'situation', 'operation', 'information', 'relationship', 'conversation'],
  nce: ['once', 'since', 'dance', 'chance', 'science', 'chances', 'evidence', 'princess', 'concerned', 'insurance', 'difference', 'experience'],
  ted: ['hated', 'wanted', 'waited', 'started', 'excited', 'invited', 'treated', 'arrested', 'expected', 'committed', 'interested', 'complicated'],
};

/** Letter bigrams by their smallest share across books, web and subtitles: the universal ones (top-200 in all three) first,
 * then the rest at >= 0.01%, each flagged. A new-key lesson with no technical target takes its headline movement from here
 * (CURR-50). Coverage data, not a difficulty score (DEC-16). */
export const COMMON_TRANSITIONS: readonly { bigram: string; minShare: number; universal: boolean }[] = [
  { bigram: 'in', minShare: 0.02021, universal: true },
  { bigram: 'th', minShare: 0.01997, universal: true },
  { bigram: 'er', minShare: 0.01787, universal: true },
  { bigram: 're', minShare: 0.01629, universal: true },
  { bigram: 'he', minShare: 0.01596, universal: true },
  { bigram: 'an', minShare: 0.01580, universal: true },
  { bigram: 'on', minShare: 0.01506, universal: true },
  { bigram: 'at', minShare: 0.01208, universal: true },
  { bigram: 'to', minShare: 0.01028, universal: true },
  { bigram: 'nd', minShare: 0.00998, universal: true },
  { bigram: 'or', minShare: 0.00991, universal: true },
  { bigram: 'st', minShare: 0.00979, universal: true },
  { bigram: 'en', minShare: 0.00959, universal: true },
  { bigram: 'ar', minShare: 0.00924, universal: true },
  { bigram: 'it', minShare: 0.00911, universal: true },
  { bigram: 'is', minShare: 0.00847, universal: true },
  { bigram: 'al', minShare: 0.00826, universal: true },
  { bigram: 'es', minShare: 0.00822, universal: true },
  { bigram: 'ng', minShare: 0.00820, universal: true },
  { bigram: 'se', minShare: 0.00812, universal: true },
  { bigram: 'ou', minShare: 0.00793, universal: true },
  { bigram: 'te', minShare: 0.00790, universal: true },
  { bigram: 'le', minShare: 0.00788, universal: true },
  { bigram: 'me', minShare: 0.00764, universal: true },
  { bigram: 'ed', minShare: 0.00703, universal: true },
  { bigram: 'ne', minShare: 0.00692, universal: true },
  { bigram: 'ea', minShare: 0.00688, universal: true },
  { bigram: 'as', minShare: 0.00653, universal: true },
  { bigram: 've', minShare: 0.00635, universal: true },
  { bigram: 'ha', minShare: 0.00618, universal: true },
  { bigram: 'li', minShare: 0.00609, universal: true },
  { bigram: 'nt', minShare: 0.00593, universal: true },
  { bigram: 'co', minShare: 0.00582, universal: true },
  { bigram: 'ri', minShare: 0.00577, universal: true },
  { bigram: 'ti', minShare: 0.00576, universal: true },
  { bigram: 'll', minShare: 0.00549, universal: true },
  { bigram: 'om', minShare: 0.00546, universal: true },
  { bigram: 'ur', minShare: 0.00539, universal: true },
  { bigram: 'ca', minShare: 0.00538, universal: true },
  { bigram: 'el', minShare: 0.00530, universal: true },
  { bigram: 'of', minShare: 0.00528, universal: true },
  { bigram: 'hi', minShare: 0.00510, universal: true },
  { bigram: 'ro', minShare: 0.00507, universal: true },
  { bigram: 'ma', minShare: 0.00502, universal: true },
  { bigram: 'ho', minShare: 0.00485, universal: true },
  { bigram: 'no', minShare: 0.00459, universal: true },
  { bigram: 'ta', minShare: 0.00458, universal: true },
  { bigram: 'us', minShare: 0.00454, universal: true },
  { bigram: 'ot', minShare: 0.00442, universal: true },
  { bigram: 'de', minShare: 0.00439, universal: true },
  { bigram: 'fo', minShare: 0.00424, universal: true },
  { bigram: 'et', minShare: 0.00413, universal: true },
  { bigram: 'ch', minShare: 0.00410, universal: true },
  { bigram: 'be', minShare: 0.00408, universal: true },
  { bigram: 'so', minShare: 0.00398, universal: true },
  { bigram: 'lo', minShare: 0.00387, universal: true },
  { bigram: 'ge', minShare: 0.00385, universal: true },
  { bigram: 'ee', minShare: 0.00378, universal: true },
  { bigram: 'il', minShare: 0.00376, universal: true },
  { bigram: 'di', minShare: 0.00369, universal: true },
  { bigram: 'ce', minShare: 0.00354, universal: true },
  { bigram: 'ra', minShare: 0.00345, universal: true },
  { bigram: 'ad', minShare: 0.00344, universal: true },
  { bigram: 'pe', minShare: 0.00344, universal: true },
  { bigram: 'la', minShare: 0.00342, universal: true },
  { bigram: 'ac', minShare: 0.00341, universal: true },
  { bigram: 'ic', minShare: 0.00339, universal: true },
  { bigram: 'ut', minShare: 0.00337, universal: true },
  { bigram: 'un', minShare: 0.00330, universal: true },
  { bigram: 'si', minShare: 0.00329, universal: true },
  { bigram: 'wi', minShare: 0.00322, universal: true },
  { bigram: 'mo', minShare: 0.00316, universal: true },
  { bigram: 'sh', minShare: 0.00315, universal: true },
  { bigram: 'rs', minShare: 0.00311, universal: true },
  { bigram: 'ai', minShare: 0.00301, universal: true },
  { bigram: 'ow', minShare: 0.00299, universal: true },
  { bigram: 'we', minShare: 0.00281, universal: true },
  { bigram: 'am', minShare: 0.00281, universal: true },
  { bigram: 'ol', minShare: 0.00274, universal: true },
  { bigram: 'mi', minShare: 0.00273, universal: true },
  { bigram: 'ie', minShare: 0.00271, universal: true },
  { bigram: 'ss', minShare: 0.00269, universal: true },
  { bigram: 'id', minShare: 0.00268, universal: true },
  { bigram: 'ir', minShare: 0.00255, universal: true },
  { bigram: 'tr', minShare: 0.00253, universal: true },
  { bigram: 'wa', minShare: 0.00249, universal: true },
  { bigram: 'na', minShare: 0.00248, universal: true },
  { bigram: 'ni', minShare: 0.00247, universal: true },
  { bigram: 'em', minShare: 0.00245, universal: true },
  { bigram: 'ig', minShare: 0.00244, universal: true },
  { bigram: 'ec', minShare: 0.00243, universal: true },
  { bigram: 'ry', minShare: 0.00241, universal: true },
  { bigram: 'ly', minShare: 0.00241, universal: true },
  { bigram: 'fi', minShare: 0.00240, universal: true },
  { bigram: 'ul', minShare: 0.00236, universal: true },
  { bigram: 'pl', minShare: 0.00236, universal: true },
  { bigram: 'rt', minShare: 0.00234, universal: true },
  { bigram: 'io', minShare: 0.00232, universal: true },
  { bigram: 'im', minShare: 0.00232, universal: true },
  { bigram: 'ab', minShare: 0.00230, universal: true },
  { bigram: 'ev', minShare: 0.00225, universal: true },
  { bigram: 'sa', minShare: 0.00218, universal: true },
  { bigram: 'ay', minShare: 0.00217, universal: true },
  { bigram: 'ke', minShare: 0.00212, universal: true },
  { bigram: 'oo', minShare: 0.00210, universal: true },
  { bigram: 'pr', minShare: 0.00207, universal: true },
  { bigram: 'os', minShare: 0.00201, universal: true },
  { bigram: 'ns', minShare: 0.00201, universal: true },
  { bigram: 'fe', minShare: 0.00199, universal: true },
  { bigram: 'pa', minShare: 0.00197, universal: true },
  { bigram: 'od', minShare: 0.00195, universal: true },
  { bigram: 'bo', minShare: 0.00195, universal: true },
  { bigram: 'av', minShare: 0.00190, universal: true },
  { bigram: 'ld', minShare: 0.00189, universal: true },
  { bigram: 'op', minShare: 0.00189, universal: true },
  { bigram: 'do', minShare: 0.00188, universal: true },
  { bigram: 'su', minShare: 0.00186, universal: true },
  { bigram: 'fr', minShare: 0.00181, universal: true },
  { bigram: 'wh', minShare: 0.00181, universal: true },
  { bigram: 'gh', minShare: 0.00180, universal: true },
  { bigram: 'ct', minShare: 0.00180, universal: true },
  { bigram: 'iv', minShare: 0.00180, universal: true },
  { bigram: 'po', minShare: 0.00178, universal: true },
  { bigram: 'nc', minShare: 0.00177, universal: true },
  { bigram: 'wo', minShare: 0.00176, universal: true },
  { bigram: 'ov', minShare: 0.00176, universal: true },
  { bigram: 'bu', minShare: 0.00173, universal: true },
  { bigram: 'tt', minShare: 0.00171, universal: true },
  { bigram: 'ap', minShare: 0.00166, universal: true },
  { bigram: 'bl', minShare: 0.00161, universal: true },
  { bigram: 'if', minShare: 0.00160, universal: true },
  { bigram: 'rd', minShare: 0.00157, universal: true },
  { bigram: 'ts', minShare: 0.00155, universal: true },
  { bigram: 'da', minShare: 0.00151, universal: true },
  { bigram: 'gi', minShare: 0.00151, universal: true },
  { bigram: 'yo', minShare: 0.00150, universal: true },
  { bigram: 'ag', minShare: 0.00148, universal: true },
  { bigram: 'uc', minShare: 0.00148, universal: true },
  { bigram: 'ba', minShare: 0.00146, universal: true },
  { bigram: 'fa', minShare: 0.00143, universal: true },
  { bigram: 'tu', minShare: 0.00141, universal: true },
  { bigram: 'vi', minShare: 0.00138, universal: true },
  { bigram: 'up', minShare: 0.00136, universal: true },
  { bigram: 'go', minShare: 0.00132, universal: true },
  { bigram: 'ht', minShare: 0.00130, universal: true },
  { bigram: 'pp', minShare: 0.00128, universal: true },
  { bigram: 'ff', minShare: 0.00128, universal: true },
  { bigram: 'ey', minShare: 0.00126, universal: true },
  { bigram: 'gr', minShare: 0.00122, universal: true },
  { bigram: 'ep', minShare: 0.00121, universal: true },
  { bigram: 'rr', minShare: 0.00121, universal: true },
  { bigram: 'ga', minShare: 0.00119, universal: true },
  { bigram: 'au', minShare: 0.00119, universal: true },
  { bigram: 'ex', minShare: 0.00118, universal: true },
  { bigram: 'ck', minShare: 0.00118, universal: true },
  { bigram: 'pi', minShare: 0.00117, universal: true },
  { bigram: 'sp', minShare: 0.00113, universal: true },
  { bigram: 'ru', minShare: 0.00109, universal: true },
  { bigram: 'ty', minShare: 0.00107, universal: true },
  { bigram: 'rn', minShare: 0.00106, universal: true },
  { bigram: 'cr', minShare: 0.00103, universal: true },
  { bigram: 'ci', minShare: 0.00102, universal: true },
  { bigram: 'ds', minShare: 0.00102, universal: true },
  { bigram: 'bi', minShare: 0.00100, universal: true },
  { bigram: 'ew', minShare: 0.00099, universal: true },
  { bigram: 'ki', minShare: 0.00098, universal: true },
  { bigram: 'mp', minShare: 0.00097, universal: true },
  { bigram: 'ys', minShare: 0.00097, universal: true },
  { bigram: 'cl', minShare: 0.00093, universal: true },
  { bigram: 'ef', minShare: 0.00093, universal: true },
  { bigram: 'ia', minShare: 0.00090, universal: true },
  { bigram: 'by', minShare: 0.00090, universal: true },
  { bigram: 'ls', minShare: 0.00090, universal: true },
  { bigram: 'br', minShare: 0.00112, universal: false },
  { bigram: 'mu', minShare: 0.00100, universal: false },
  { bigram: 'ny', minShare: 0.00098, universal: false },
  { bigram: 'tl', minShare: 0.00098, universal: false },
  { bigram: 'ak', minShare: 0.00097, universal: false },
  { bigram: 'ye', minShare: 0.00093, universal: false },
  { bigram: 'fu', minShare: 0.00092, universal: false },
  { bigram: 'ob', minShare: 0.00091, universal: false },
  { bigram: 'oi', minShare: 0.00088, universal: false },
  { bigram: 'rk', minShare: 0.00088, universal: false },
  { bigram: 'ue', minShare: 0.00088, universal: false },
  { bigram: 'ei', minShare: 0.00087, universal: false },
  { bigram: 'sc', minShare: 0.00087, universal: false },
  { bigram: 'rl', minShare: 0.00086, universal: false },
  { bigram: 'ug', minShare: 0.00086, universal: false },
  { bigram: 'gu', minShare: 0.00086, universal: false },
  { bigram: 'dr', minShare: 0.00085, universal: false },
  { bigram: 'cu', minShare: 0.00084, universal: false },
  { bigram: 'oc', minShare: 0.00082, universal: false },
  { bigram: 'pu', minShare: 0.00081, universal: false },
  { bigram: 'um', minShare: 0.00080, universal: false },
  { bigram: 'nn', minShare: 0.00073, universal: false },
  { bigram: 'eo', minShare: 0.00072, universal: false },
  { bigram: 'hr', minShare: 0.00072, universal: false },
  { bigram: 'qu', minShare: 0.00071, universal: false },
  { bigram: 'lu', minShare: 0.00069, universal: false },
  { bigram: 'wn', minShare: 0.00067, universal: false },
  { bigram: 'ft', minShare: 0.00067, universal: false },
  { bigram: 'ui', minShare: 0.00067, universal: false },
  { bigram: 'mb', minShare: 0.00066, universal: false },
  { bigram: 'rg', minShare: 0.00065, universal: false },
  { bigram: 'ok', minShare: 0.00064, universal: false },
  { bigram: 'rm', minShare: 0.00063, universal: false },
  { bigram: 'af', minShare: 0.00063, universal: false },
  { bigram: 'my', minShare: 0.00062, universal: false },
  { bigram: 'aw', minShare: 0.00060, universal: false },
  { bigram: 'ju', minShare: 0.00059, universal: false },
  { bigram: 'nl', minShare: 0.00058, universal: false },
  { bigram: 'nu', minShare: 0.00058, universal: false },
  { bigram: 'hu', minShare: 0.00057, universal: false },
  { bigram: 'tw', minShare: 0.00057, universal: false },
  { bigram: 'ua', minShare: 0.00056, universal: false },
  { bigram: 'ip', minShare: 0.00054, universal: false },
  { bigram: 'og', minShare: 0.00054, universal: false },
  { bigram: 'jo', minShare: 0.00054, universal: false },
  { bigram: 'lf', minShare: 0.00053, universal: false },
  { bigram: 'eg', minShare: 0.00052, universal: false },
  { bigram: 'nk', minShare: 0.00052, universal: false },
  { bigram: 'mm', minShare: 0.00051, universal: false },
  { bigram: 'gs', minShare: 0.00051, universal: false },
  { bigram: 'oa', minShare: 0.00051, universal: false },
  { bigram: 'ud', minShare: 0.00049, universal: false },
  { bigram: 'dy', minShare: 0.00048, universal: false },
  { bigram: 'lt', minShare: 0.00048, universal: false },
  { bigram: 'ks', minShare: 0.00048, universal: false },
  { bigram: 'sl', minShare: 0.00047, universal: false },
  { bigram: 'ph', minShare: 0.00046, universal: false },
  { bigram: 'ps', minShare: 0.00044, universal: false },
  { bigram: 'pt', minShare: 0.00044, universal: false },
  { bigram: 'ik', minShare: 0.00043, universal: false },
  { bigram: 'dd', minShare: 0.00043, universal: false },
  { bigram: 'du', minShare: 0.00042, universal: false },
  { bigram: 'ub', minShare: 0.00042, universal: false },
  { bigram: 'fl', minShare: 0.00042, universal: false },
  { bigram: 'rc', minShare: 0.00041, universal: false },
  { bigram: 'va', minShare: 0.00041, universal: false },
  { bigram: 'ms', minShare: 0.00041, universal: false },
  { bigram: 'sk', minShare: 0.00039, universal: false },
  { bigram: 'hy', minShare: 0.00039, universal: false },
  { bigram: 'oe', minShare: 0.00039, universal: false },
  { bigram: 'ib', minShare: 0.00038, universal: false },
  { bigram: 'sm', minShare: 0.00037, universal: false },
  { bigram: 'gl', minShare: 0.00037, universal: false },
  { bigram: 'sy', minShare: 0.00037, universal: false },
  { bigram: 'kn', minShare: 0.00036, universal: false },
  { bigram: 'oy', minShare: 0.00036, universal: false },
  { bigram: 'je', minShare: 0.00035, universal: false },
  { bigram: 'vo', minShare: 0.00034, universal: false },
  { bigram: 'wr', minShare: 0.00031, universal: false },
  { bigram: 'gn', minShare: 0.00030, universal: false },
  { bigram: 'ze', minShare: 0.00029, universal: false },
  { bigram: 'rv', minShare: 0.00029, universal: false },
  { bigram: 'yi', minShare: 0.00029, universal: false },
  { bigram: 'ws', minShare: 0.00029, universal: false },
  { bigram: 'xp', minShare: 0.00028, universal: false },
  { bigram: 'eb', minShare: 0.00027, universal: false },
  { bigram: 'iz', minShare: 0.00027, universal: false },
  { bigram: 'xt', minShare: 0.00027, universal: false },
  { bigram: 'rf', minShare: 0.00027, universal: false },
  { bigram: 'tc', minShare: 0.00026, universal: false },
  { bigram: 'cc', minShare: 0.00026, universal: false },
  { bigram: 'ja', minShare: 0.00026, universal: false },
  { bigram: 'dl', minShare: 0.00025, universal: false },
  { bigram: 'gg', minShare: 0.00025, universal: false },
  { bigram: 'nf', minShare: 0.00025, universal: false },
  { bigram: 'xc', minShare: 0.00024, universal: false },
  { bigram: 'nv', minShare: 0.00024, universal: false },
  { bigram: 'sw', minShare: 0.00024, universal: false },
  { bigram: 'rp', minShare: 0.00022, universal: false },
  { bigram: 'oh', minShare: 0.00021, universal: false },
  { bigram: 'lm', minShare: 0.00020, universal: false },
  { bigram: 'lk', minShare: 0.00020, universal: false },
  { bigram: 'eh', minShare: 0.00020, universal: false },
  { bigram: 'lp', minShare: 0.00019, universal: false },
  { bigram: 'uf', minShare: 0.00019, universal: false },
  { bigram: 'ix', minShare: 0.00018, universal: false },
  { bigram: 'bs', minShare: 0.00017, universal: false },
  { bigram: 'tm', minShare: 0.00017, universal: false },
  { bigram: 'cy', minShare: 0.00017, universal: false },
  { bigram: 'ka', minShare: 0.00017, universal: false },
  { bigram: 'yt', minShare: 0.00017, universal: false },
  { bigram: 'hn', minShare: 0.00017, universal: false },
  { bigram: 'ek', minShare: 0.00016, universal: false },
  { bigram: 'lv', minShare: 0.00016, universal: false },
  { bigram: 'ya', minShare: 0.00016, universal: false },
  { bigram: 'dg', minShare: 0.00016, universal: false },
  { bigram: 'xa', minShare: 0.00015, universal: false },
  { bigram: 'eu', minShare: 0.00014, universal: false },
  { bigram: 'ym', minShare: 0.00014, universal: false },
  { bigram: 'ah', minShare: 0.00014, universal: false },
  { bigram: 'rb', minShare: 0.00014, universal: false },
  { bigram: 'lw', minShare: 0.00013, universal: false },
  { bigram: 'ax', minShare: 0.00013, universal: false },
  { bigram: 'az', minShare: 0.00012, universal: false },
  { bigram: 'py', minShare: 0.00012, universal: false },
  { bigram: 'xi', minShare: 0.00011, universal: false },
  { bigram: 'bb', minShare: 0.00011, universal: false },
  { bigram: 'hs', minShare: 0.00011, universal: false },
  { bigram: 'lc', minShare: 0.00011, universal: false },
  { bigram: 'kl', minShare: 0.00010, universal: false },
  { bigram: 'rh', minShare: 0.00010, universal: false },
  { bigram: 'lr', minShare: 0.00010, universal: false },
];

/** Everyday words (SUBTLEX-US frequent, in many films, mostly lower-case, in the Google Books list, not excluded), most
 * frequent first — the research practice-word filter applied to the whole vocabulary. */
export const EVERYDAY_WORDS: readonly string[] = (
  'you the to a it that and of in me is we this he on for ' +
  'my your have do be know was not can are all with just get here but ' +
  'there so they right like out go she up about if him got at now one ' +
  'her want think good see did who as his will going from when back time look ' +
  'take an man them would been some tell or us had were say could really something ' +
  'down then little way our make too never by over more need mean very off sorry ' +
  'give has love said people please sure any thing only because two should doing much sir ' +
  'help anything these even night call talk nothing into first find wait put great thought day ' +
  'work life before better again still home guy those than around other away new last ever ' +
  'stop keep told must things big after long does always their everything nice name money guys ' +
  'feel believe old place fine kind lot years made leave girl hear father through every bad ' +
  'remember three boy coming wrong might stay house may baby another wanted enough talking happened show ' +
  'course being care done getting mind left ask car understand mother which try came own world ' +
  'guess next kill else dead trying someone real room morning huh hold woman yourself today looking ' +
  'friend move same job tonight went son best saw found pretty ready heard whole seen together ' +
  'minute men head matter knew many idea without play family meet most run while wife once ' +
  'live somebody everybody used use myself took yet start called kid tomorrow happy school problem watch ' +
  'bring actually business says hope open already since looks sit cause alone hard wants stuff turn ' +
  'days friends until few kids honey gone both door later saying such killed having face worry ' +
  'ago five second brother case thinking probably beautiful hand check year forget hit lost minutes crazy ' +
  'late phone end easy doctor under part deal die soon four anyone pay happen true each ' +
  'supposed eat mine working town afraid drink exactly whatever hurt knows heart gave young everyone chance ' +
  'read makes number taking change anyway week married hands point police word fun wish bit game ' +
  'party set cut comes sleep shot anybody ass stand water boys trouble dear couple gets making ' +
  'eyes break story far times close means funny goes lady death asked walk fire hours hate ' +
  'gun rest person inside waiting different girls least important also line yours office dinner quite against ' +
  'fight side six half pick question ahead cool women body high husband reason almost dog buy ' +
  'truth met telling hot anymore behind started speak bed moment tried blood shall stupid along either ' +
  'though front sister send welcome sometimes trust free book answer between children war fact brought bet ' +
  'clear its white glad daughter outside city feeling black seems full till sick light shoot news ' +
  'lose wonderful months save hour country needs able perfect running child died order living sounds alive ' +
  'food gentlemen luck hair drive promise sex music power sort special serious street red dance hang ' +
  'touch team playing company pull plan sweet ten coffee lucky sound safe date leaving parents himself ' +
  'seem lives air taken picture ladies sent fast happens catch ride win kidding top scared dream ' +
  'sign meeting sense beat control drop cold weeks darling figure king poor throw asking write suppose ' +
  'small human piece boss hospital past calling known follow movie straight words clean kiss looked feet ' +
  'evening million lie felt moving certainly step learn fall questions finally takes class quiet wonder law ' +
  'become worked rather possible unless mad absolutely tired murder road eye except somewhere explain less none ' +
  'loved giving seeing secret wear worth act careful quick handle pass early report state busy turned ' +
  'table wake works broke ball seven mouth marry meant fault lunch expect future paper officer hotel ' +
  'buddy thinks talked blue mistake ones wedding clothes weird changed court floor watching building earth dude ' +
  'others longer finish forgot ship club attention eight worse pain sing blow choice birthday stick relax ' +
  'yesterday honor smart boat plane month lovely given train fair worried needed sitting security cover across ' +
  'bag terrible caught song spend horse ring sell return personal message system afternoon happening tough quit ' +
  'count box missed present charge kept information fool simple middle calm surprise forever decided dark anywhere ' +
  'miles swear land missing cute lying master dress key strong fix interesting wearing strange rock voice ' +
  'cop window bar totally interested appreciate army paid short record bought card certain college evidence fly ' +
  'bank completely ran cops test history finished born proud fish join lead smell near apartment enjoy ' +
  'letter situation trip store amazing star accident imagine ought pleasure list rich calls service entire difference ' +
  'judge ice lawyer fat instead age station realize gold seat liked hundred summer dollars standing mess ' +
  'killing radio hungry problems marriage brain soul forgive drunk deep figured likes girlfriend folks slow private ' +
  'during attack beer definitely stopped partner walking area dangerous offer scene third upset bus owe shoes ' +
  'driving group kick evil joke fell truck teach green ground loves cash forward honest boyfriend park ' +
  'position single respect broken crime wrote public grab art fighting favor upstairs wall force seconds jail ' +
  'push prove normal machine protect field spent feels speaking named jump saved starting nose hide church ' +
  'sun peace share moved picked thousand holding fear using tape suit pictures putting involved gas books ' +
  'relationship neither nine rules bother especially nervous whether dying stuck round dirty cat breakfast idiot space ' +
  'lived prison carry bastard cry smoke arm film government tree foot contact knock agree pardon gift ' +
  'gives dreams hat board sake sweetheart seriously department patient awful sad wondering roll beginning grand usually ' +
  'killer laugh doubt listening upon double twice whose outta plenty guilty promised fired race crap chicken ' +
  'bathroom spot reading orders weekend action eating glass type guns experience obviously wine press difficult lots ' +
  'rid sea arms flight staying arrest neck grow mention favorite wind sleeping notice admit extra within ' +
  'low impossible gay computer angry bunch blame pants visit clock tea fellow kitchen lay hole guard ' +
  'learned smile feelings fit pal bear often wild silly camera begin reach beach heaven lock leg ' +
  'quickly lights worst shooting played plans bucks suddenly writing track teacher ridiculous legs river dare burn ' +
  'raise decision surprised cross cost queen fresh innocent emergency dancing medical cell gotten seemed bigger closed ' +
  'names walked bomb hanging note shop sweetie nuts band losing price steal waste client stole code ' +
  'crying pressure places dogs accept further excellent magic drinking keeps corner consider ourselves acting herself locked ' +
  'laughing address copy tells warm sold pregnant hall treat everywhere papers complete cup level ways passed ' +
  'witness taste hardly camp keeping keys beg duty interest tight bottle helping support flying decide turns ' +
  'moon bottom hoping conversation hero asleep final continue match apologize trial spirit willing chair risk study ' +
  'possibly rain above cousin pulled cream dropped excited memory breathe enemy huge search drugs greatest beauty ' +
  'lately rule build choose cards advice immediately teeth became victim coach flowers showed crew driver heavy ' +
  'trick empty comfortable destroy brothers mission apart pool dumb dressed helped knife checked weapon restaurant shirt ' +
  'faith simply dig size stars movies necessary themselves blind credit center starts bridge practice closer discuss ' +
  'cars mister cook stage strike ticket animal bird leaves sight following somehow knowing drug career nature ' +
  'cake responsible famous nurse correct breath games allowed sky bringing hearing singing account common due afford ' +
  'tie bright allow belong concerned escape suspect written file skin madam fill operation desk taught pack ' +
  'lied faster deserve danger meat command stories tickets hiding paying perfectly whoever beyond student dry jury ' +
  'form main heads program milk held horrible kinda feed natural battle breaking ugly coat settle opinion ' +
  'terrific gentleman older loose noticed local lonely shame shows large devil video speed military built shower ' +
  'oil opportunity chest horses biggest threw bite wash stone block records indeed weapons invited draw turning ' +
  'attorney pretend health balls heat manager guest loud fantastic itself cares shake lab numbers princess island ' +
  'easier color earlier bell naked suggest wet pig letting nowhere animals cheese ideas downstairs soldier monster ' +
  'several planet fellas insane eggs spoke butt murdered view bloody lines opening insurance split jealous bullet ' +
  'arrived character national screaming airport speech hook condition target finding serve incredible player signal sugar total ' +
  'selling hill football page screw justice letters hurts project rough crowd meaning planning pair science sees ' +
  'usual sooner ordered subject lies remind strength mail paint freak bedroom neighborhood onto finger personally spell ' +
  'ghost doctors fake release weight cheap market pray expecting unit signed falling throat lake nor director ' +
  'realized agreed truly brilliant cab powers candy prepared legal pocket aware roof babe slept responsibility mountain ' +
  'base ours firm trade whom romantic fan liar training brings powerful language sending whenever purpose believed ' +
  'bless pieces arrested noise suck fancy exciting genius forgotten introduce rent familiar criminal doors proof vote ' +
  'com recognize stolen suicide weather drinks medicine issue lift followed buried mood male among television nights ' +
  'regular opened someday stomach yellow ate nearly scare village prepare matters monkey pizza assume heading sudden ' +
  'toast ears fella babies jacket social thoughts travel sometime property expected fingers bodies remain secretary funeral ' +
  'magazine sexual jerk dating glasses freedom research add damage handsome repeat hired buying prefer society energy ' +
  'crack chase vacation divorce stayed defense rat began picking checking goodness reasons post confused surgery telephone ' +
  'contract safety tall fixed professional lesson assistant tiny points understood runs license model gate soft ear ' +
  'riding staff warning engine planned map swim harm square silver brave access positive covered female someplace ' +
  'streets blew weak season rush awesome snow spring champagne spread mayor pounds demon winner lips leader ' +
  'tongue bath permission showing storm destroyed spare tour headed trees students ends bones burning appointment kicked ' +
  'mentioned score shoe ocean harder reality shape gang survive saving cos style farm shopping clearly sexy ' +
  'answers example growing laid gosh rings alarm plays screwed fortune schedule bleeding enter punch ended patients ' +
  'rights invite obvious charges interview touched affair parts unbelievable wherever chocolate focus borrow grade grew finds ' +
  'investigation mate statement load painting throwing community loss waited barely woods changes details yourselves exist toilet ' +
  'chances drove meal dump disappeared member shock discovered failed pie crash artist sat theory depends bags ' +
  'joy pleased ruin kissed traffic nonsense pink wise carrying burned midnight shots deliver bread officers button ' +
  'dealing original hated source cases hung received charming switch decent below desert process expensive belongs particular ' +
  'higher moves breathing grandmother lower period pride dollar thousands witch soldiers tip jobs plant sports surely ' +
  'bust birth including joint bull wire brains rise towards boring ashamed sisters section facts clever smells ' +
  'honestly success garage connection filled physical complicated pulling regret closet loser giant wheel parking policy stranger ' +
  'tear wood fate juice governor tied faces awake fought coast pilot miracle aboard files lover based ' +
  'cigarette disgusting grateful mighty murderer garden watched wound drag forced fourth scream event woke actor row ' +
  'grave changing senior curious flat winter badly priest scary shoulder super disease sword chick smoking closing ' +
  'offered concern talent garbage attitude mostly bone egg friendly recently basically engaged quarter thee rooms passing ' +
  'swing available bike birds knees slip hunt caused taxi stood likely object hates percent raised guests ' +
  'desperate dirt pussy negative plate cooking data distance tank request golf hire knowledge ruined cow dawn ' +
  'falls stock equipment conference reports rescue claim sale audience silence warn mercy create proper universe baseball ' +
  'soup outfit slowly yard grown loving pure rate bro dies celebrate piano pills uniform stealing spending ' +
  'doll duck location returned amount healthy knocked pen reached walls steps younger attractive notes fail beast ' +
  'path poison wanting naturally happiness anytime sucks eventually channel elevator thy belt grandfather secure avoid penny ' +
  'laughs thief guards bride pathetic mirror partners becomes dozen direction gorgeous direct odd theater committed led ' +
  'march members official puts attacked effect tail treated vision secrets dust talks trap wide honour sharp ' +
  'aside deck stairs guts extremely lousy unusual newspaper apple courage terribly fishing carefully hitting pulse writer ' +
  'edge illegal pity couch protection tests staring victims created screen appear winning precious studio windows kissing ' +
  'rob golden frightened owner royal intend considered parties cast prisoner popular destiny robbery federal silent violence ' +
  'hearts mystery nerve circumstances library toward busted becoming rocks embarrassing photo practically tower armed friendship maid ' +
  'shift wallet package flower range beating results rope steady cleaning exact image turkey vehicle easily jungle ' +
  'nasty pot sensitive suffer millions remembered trash thou ambulance behavior nightmare prize per snake tears cancer ' +
  'families orange terms foreign media wasting memories songs material expert cutting advantage flesh rude disappointed committee ' +
  'guarantee signs kinds punk downtown sandwich marks understanding mistakes political sweat cents panic performance plain boom ' +
  'stops union seats cable fruit hundreds separate ancient underwear moments castle rolling setting delicious circle value ' +
  'bills glory miserable squad counting manage bowl victory zero embarrassed stands creature basketball deny mixed continues ' +
  'route rare yelling holiday hidden ill directly helps progress remove wave gods authority chain emotional highly ' +
  'hunting wore shadow false jumped gray estate skip whore horn agents appears basement minds pleasant clients ' +
  'mile approach refuse disappear bug district rabbit speaks champion competition proceed stopping forces leading presence century ' +
  'cure capable convinced swell warrant threat therefore bury diamond services shine bat alert chip transfer sentence ' +
  'thrown fabulous nation pushed butter jokes reporter booth casino successful learning awfully possibility sand bow cage ' +
  'desire wolf units wing exchange trapped bored pet thin drama rip series hills homework carried entirely ' +
  'zone explanation spy assure failure collect hits bang swimming launch print delivery fever journey useless photos ' +
  'kills sport challenge loan routine soda spoken mask teaching trunk leads passion purse result argue climb ' +
  'served cats beef witnesses recall wings cabin mental ships script article solid education salt solve confidence ' +
  'frankly metal receive wounded agency anger escaped settled suffering detail pipe trace supper wins effort spit ' +
  'studying hug enemies treatment commit intelligence reputation troops custody ability site fifth palace trail pushing boots ' +
  'hop stays owns attempt houses lawyers mouse bout ease hurting stronger considering ordinary presents customers impressed ' +
  'laundry ripped treasure revenge odds tricks cowboy nuclear motion mall virus forest sounded trained scratch virgin ' +
  'breaks fifty potential defend contest fashion plastic cap convince interrupt latest issues arrive cheer chose supply ' +
  'surveillance ignore mountains nail league vice figures joking cheating coincidence favour loaded messages quality title division ' +
  'impression particularly reasonable tiger therapy bastards museum minister steel bound slave standard wishes anniversary dreaming yell ' +
  'firing reminds shy cruel walks seek cancel chasing prime former smooth socks dates modern surface curse ' +
  'lifetime role chosen eaten gym motel collection device enjoyed heck pee noon blowing sons reward degrees ' +
  'lets bothering bars cameras dumped iron express cookies sacrifice assignment tunnel highway guide insist slide specific ' +
  'wrap cleaned prom wagon cigarettes lack defendant exercise packed bullets cheat kit background ringing clue damned ' +
  'assault concert ranch suits temple designed planes vampire foolish agreement darkness flag tent rotten remains term ' +
  'alien patch provide touching snap bail believes imagination actual incident liquor released connected disaster fully mass ' +
  'comfort sec smiling border fuel legend players crossed electric demand opera circus current diamonds trauma enjoying ' +
  'laws neighbors prints salad argument describe impressive starving neighbor council fallen sink backup screams sneak trigger ' +
  'wipe events tone toy youth crush factory campaign grass instance searching trusted goal tracks wasted messed ' +
  'asks cookie generous fairy violent average crisis humor liberty suite opens rats slipped systems stake gambling ' +
  'managed nephew alcohol politics threatened begins gentle occasion network unhappy cleared charity confession explosion joined finest ' +
  'offense headquarters judgment shout filthy surgeon tube hon kidnapped math operator personnel pin mix sucker alley ' +
  'dancer dealer humans chat depressed hoped reaction commercial mon underneath behave chill chips fantasy gloves steak ' +
  'version sides worrying design dropping experiment honeymoon struck blast identify arranged classic quarters crystal delivered procedure ' +
  'spirits whiskey divorced perform prisoners response dope fence greater poker landing normally powder actress drawing protecting ' +
  'gear rape advance locker suspicious civil sin classes ending marrying torture banks blown personality selfish dough ' +
  'fed confess deserves warned ceremony clown solution tries helicopter costs prayer apology dressing forth invented hers ' +
  'accepted boxes entrance singer strip gather concentrate deputy instructions satellite uncomfortable daily nut stress tune guitar ' +
  'kicking merely pretending sauce sighs valuable basic belly charm exit blows net voices patrol pitch romance ' +
  'arrange satisfied makeup teams surrender rub strangers whistle bum kingdom visiting wives hip flew hood diet ' +
  'dreamed junk patience earn flash lion frozen homicide robbed decisions gross holes badge uses financial offering ' +
  'answered customer officially opposite soap beside privacy unknown anyhow painful represent lessons champ extraordinary pour reported ' +
  'testing hopes twins fascinating furniture meantime rice squeeze bend beats begging host blocks mysterious sore balance ' +
  'shark timing technology angle sets guilt wondered yards checks degree invitation knocking aim urgent movement mud ' +
  'review freaking influence moron souls product seal tap testimony broad films skull status escort knee recording ' +
  'stretch territory affairs entered listened murders spin favourite angels noble relief sample shouting hostage rifle skills ' +
  'chicks tax deaf port sticking literally technically foul habit pattern charged occurred removed beans confirm deeply ' +
  'lad option coward benefit brief gifts awkward adult liver bombs drives flip holds jumping ward counsel ' +
  'corn debt gal international testify traveling cared childhood cotton facility roses shown tragedy admire brush homes ' +
  'pro self towel costume jet lightning bush prick anxious frame headache respond ghosts washed flies supplies ' +
  'wounds answering attend dessert options pays sacred afterwards clinic recommend rubber schools cave remote skinny thick ' +
  'brand culture fans polite blonde claims painted theme aid conscience counter darn oxygen pound tag machines ' +
  'religion religious combat construction audition blessed laughter sweater commission dame shave temperature drill flow principal sail ' +
  'gain crown packing granted tradition wreck poem species unique zoo bugs pages similar tennis chop muscle ' +
  'sticks barn cherry leather tooth counts cheering emperor jam confirmed intelligent moral lap blah steam adventure ' +
  'punishment sheep exam gates penis demons gum suitcase bottles equal operate poetry struggle fools replace citizen ' +
  'freezing grabbed possession smaller thunder abandoned halfway pigs session wheels wicked heavens interests surrounded digging fellows ' +
  'paradise motive palm cattle hut magnificent pit shell shove toys waves stable stink waiter basket nurses ' +
  'pile tracking bells determined marvelous motor musical sire whip missile parent complex hooked monitor recent useful ' +
  'incredibly organization backwards stroke accused engagement prevent chuckles goose messing rap temporary limit phones tapes appeal ' +
  'blade despite drawer propose superior blanket cried eleven identity maintain cigar delighted inches mob refused survived ' +
  'matches sack clerk properly activity appropriate award lamp parade profile resist scout shaking drank stepped suffered ' +
  'exhausted heroes comment dive fits hatch minor mistaken approaching landed authorities environment fighter handled medication beloved ' +
  'expression manners wears chamber effects swallow task capital catching sales chin conditions lobby toe tub earned ' +
  'empire highest string description developed eats nap production pump stations actors con deeper inform beard passes ' +
  'related twist bid pole typical realise remarkable bitches complain creatures entertainment soccer insult apply plates toes ' +
  'happier acts choices hammer producer sheets slap neat rehearsal suspects breasts covering railroad rear battery editor ' +
  'informed diner sailor toss inch tire bump invisible lawn peanut convention fond phase purple quietly revolution ' +
  'excitement goods item thus cheated episode forgetting pan passengers stinks thirsty tits coma cruise fooling pockets ' +
  'tend critical development tragic attached graduate handy placed sharing advise dismissed mothers signature suggestion accent labor ' +
  'robot scientist actions behalf entry buddies discussion generation helpful permanent servant assigned brass captured kidnapping permit ' +
  'terrorist widow dull upper dime psychiatrist retired crawl discover fights joining vault lemon underground bargain criminals ' +
  'loyal tale beaten combination precisely tastes cells citizens employees log tattoo basis fields link relationships jazz ' +
  'needle idiots sakes chef mistress racing attracted bacon dishes psychic treating chapter farmer rocket sunshine unfortunate ' +
  'frog pill thumb comedy intended terrorists operations shoulders weed wrapped beings boats cloud feeding owned tables ' +
  'threatening transferred dated dining explained hooker policeman pops shocked undercover chopper engineer existence fries hid individual ' +
  'industry picnic reckon serving lend loyalty shelter splendid workers carpet divine management beneath introduced raped spoil ' +
  'troubles porn sheet appearance ham lazy plot betrayed crimes employee medal returning dragged reporting entering hockey ' +
  'manner waitress destruction entitled fingerprints visual newspapers sends active denied discovery dish electricity puppy cuts perfume ' +
  'shadows unconscious operating temper theatre bears companies pillow roommate stones talented teachers approve cock defeat elephant ' +
  'forms promises safer scientific alike asses assumed chemical handling photograph slut trailer attacks heal absolute killers ' +
  'practical rage serial shrink studied applause potato slightly exists gin necessarily paintings raising whale assholes creep ' +
  'peaceful warden lovers complaining dentist gig immediate straighten transport affect billion bitter boot creepy helpless include ' +
  'laying reception ages annoying brandy luggage tools assuming conduct disturb nest potatoes safely function massage wisdom ' +
  'boarding jewelry produce thrilled analysis nails delay psycho limited register election reverse shed column fetch intention ' +
  'lick nerves profit assistance booze emotions extreme verdict worker airplane bra lame promotion rhythm cocktail everyday ' +
  'rounds honored protected stubborn von clothing concept pumpkin smarter torn waters comic grief computers deposit dignity ' +
  'sixth suggesting commitment instant monsters bits passenger proved understands acted beers creative facing lip salary strictly ' +
  'throughout tool banana eternal marked required rod tissue campus guessing subway bowling laughed arguing confident engines ' +
  'homeless paranoid barrel drawn lamb privilege require wizard executive fund worries capture drown fleet lungs multiple ' +
  'separated statue traitor twisted consequences begun discussed exposed kindly payment adorable bets compared countries goat measure ' +
  'pork tested candles collar effective accounts injured lecture passport publicity root shared blond dice fixing grounds ' +
  'parked parole witches believing celebrating salesman twin booked bothered clubs crashed nanny paperwork plug rug rumor ' +
  'meetings rode tellin unlike freaked lean bee colors communication cooperate levels spots worthy wrist conspiracy enormous ' +
  'misery obsessed punished reservation sunset announcement curtain drops suggested driven fooled identified jeep locate relieved specifically ' +
  'abuse ballet blues compliment magazines naughty stiff sum unable album burger random spotted tense concerns corporate ' +
  'happily chickens gunshot impress injury intense praying borrowed brick organized priority questioning raw slight structure complaint ' +
  'fried snakes leak registered sucked warrior worm bleed corpse document dynamite glove louder sober spider survival ' +
  'vodka branch worn budget deserved envelope novel pistol relatives shortly fraud shotgun bucket clouds overnight application ' +
  'belonged experienced heels nicely buildings daughters warehouse acid butler massive menu sits skirt stare inner scholarship ' +
  'signing causes constant counselor provided solved tanks visitors centre festival imagined scum bachelor celebration chairs deadly ' +
  'depend examine oath practicing screwing ashes disturbed pencil trucks arrangements bounce causing confusing fridge internal ties ' +
  'unfair burden core heroin shining championship dummy graduation humble appeared deals dramatic explode observe photographs raining ' +
  'retire roast shooter silk announce bartender differently fires ransom coin dock dresses execution gut investment necklace ' +
  'sealed seventh surprises suspected taxes bait bald hats lit absurd blank blessing demands humanity copies directions ' +
  'fee filling grip hostages kidney scientists sworn ape atmosphere bench polish punish added connect cracked pancakes ' +
  'spray aliens floating gathered losers porch tires develop sandwiches autopsy positions requires adults burnt daylight mortal ' +
  'pace plants quote sorts terrified envy hallway relations bearing characters interfere mill niece signals cooked delicate ' +
  'lesbian loses prayers scale smack stores strikes sweep therapist grows previous retreat towels awhile cent chart ' +
  'helmet investigate scheduled aircraft arrangement farewell fathers fog physics stabbed strategy succeed discussing cows impact sailing ' +
  'scan severe shorts tons chaos civilian maniac triple types cellar covers documents flush oldest owes danced ' +
  'independent studies vessel alternative height reveal deed meets volunteer debate glorious upside error faint handed stinking ' +
  'worthless ladder groups physically telegram arts gasps hears poet resources web whatsoever amusing arrives bonus delightful ' +
  'hint stunt closely fairly horror located picks rumors admitted codes fears tips betray holidays investigating rented ' +
  'snack conclusion faithful photographer popcorn wars magical penalty phrase population recovery somewhat thieves tournament damaged disturbing ' +
  'outer chew crawling described discipline roads takin washing cart coffin explains flame perimeter profession wax kindness ' +
  'ultimate barking cargo gently terror vampires associate certificate coroner diary recognized sock swamp breast broadcast closest ' +
  'kings lighter preparing stall appetite areas barbecue crowded fluid gamble hopeless hostile obey planted ritual technique ' +
  'various dug motorcycle sins whack auction contrary weakness journal leaders oven spiritual tender worlds dial storage ' +
  'advanced grades models constantly embarrass fork quitting repair reunion accidentally apologies filed lipstick pepper cities cough ' +
  'proposal protest recovered rolls unexpected goddess hurricane mankind returns stab waking infection swore visitor wrestling beam ' +
  'cease reads anyways buttons cannon colour conflict crossing deer flu objects primary shirts shrimp cemetery balloon ' +
  'chemistry samples sexually excuses fame harmless stuffed throne tin drain electrical fold morgue pimp requested rig ' +
  'setup activities distant tan briefcase petty symbol vicious beds sleepy vulnerable banging convenient forbid hack increase ' +
  'raid reporters seated solo tension burst curiosity display scares slice threaten transmission butcher candidate communicate gallery ' +
  'invasion wee laser lunatic rank robe til compete drum ducks kiddo limo reference regarding rolled scar ' +
  'senses spill spoiled values affection chased crushed disappoint madness nickel resistance retirement tremendous adopted betting dizzy ' +
  'software anonymous haircut lads recorded rising thrill approval determine fry horny inn instincts scenes sequence courtroom ' +
  'refrigerator alibi ceiling compare judges ribs sympathy wig bare cabinet cane civilization doorbell indicate nearby pointing ' +
  'formal generally jar plague apples emotion reminded tore tramp arrival footage freaks fur infected misunderstanding philosophy ' +
  'prior scores cocaine depth illusion native phony qualified replaced residence smash tossed writes convicted lung technical ' +
  'visions wished fortunate mature perspective radiation sang sources sweating yacht genuine larger shield strings deeds insisted ' +
  'autograph dedicated judging trains doomed established minimum pad presume traditional courtesy kicks panties scandal slaves abandon ' +
  'allergic capacity consciousness girlfriends improve instrument pony ski sleeps whispering artists needing reaching hose messenger missiles ' +
  'mole versus breeze rash stream tray ankle candle couples defence devoted disgrace exception identification pale recover ' +
  'surgical worship attacking bubble circles dreadful manual pod tuna cooperation eternity floors grandson password rainbow symptoms ' +
  'chapel depression dip existed scaring searched tricky tuck watches aggressive author batteries forgiveness martini monkeys sickness ' +
  'businessman decides meals popped proves pulls skill smelled sneaking connections contacts finishing focused uniforms wandering whisper ' +
  'climbing duties hustle largest method proposition welfare ditch formula images lounge mere minus prosecution wiped accurate ' +
  'arrow assist attic backs forehead sis votes apologise defending groom saddle bracelet communications controls destroying disguise ' +
  'exclusive flattered kisses shiny thoughtful cue embassy gossip grounded hamburger rack relative sausage soil creating husbands ' +
  'institution maximum vital addition aspirin bore graduated gratitude liquid principle theirs adore arriving blackmail persons poisoned ' +
  'rot corporation expenses remembers rider risky shaft attempted deaths receiving auto cans completed drowned insanity interrupting ' +
  'sunny switched groans importance inspired instinct magician passage sub terminal content pickup pilots unto zip belief ' +
  'exhibit legally recipe spite spoon administration chains forbidden pointed stove declare embrace karate masters nations possibilities ' +
  'seed wired bass bold genetic muscles peanuts peculiar prep prostitute react trophy violation accomplished legitimate offended ' +
  'savings throws winds hunch offers backed bombing centuries chili ego flames included ink jolly nearest nicer ' +
  'protocol rum skies ton umbrella carriage executed float mobile sings tortured approximately chess expense favors observation ' +
  'outstanding potion advertising aisle bathing benefits concrete consent contacted dealt gesture guessed haunted occur racket receipt ' +
  'anchor income injuries pipes ruining colored cousins cursed distracted heel logical weekends guidance heights monk prescription ' +
  'prices sucking wealthy bothers brutal efforts fist freshman pirate regard sharks tide tops achieve boobs ideal ' +
  'lobster owed precinct puzzle refer resident spinning agenda balcony breakdown casual casualties melt misses performed suspended ' +
  'suspicion armor bizarre canceled celebrity claimed clears panel begged distress draft follows illness jammed nightmares shitty ' +
  'boxing continued elected factor gathering jewels organ salute scheme tick whipped abortion backyard dorm honorable jewel ' +
  'liable ordering bent bully drowning honesty mutual platoon presentation rally standards annual drums integrity inviting limits ' +
  'nailed notify posted published scrambled trips wooden bounty demonstration intentions prosecutor quicker rely reserve rides ants ' +
  'cheek folk gracious noises savage amongst attending disorder fuss jaw occasionally substance calendar carnival confusion jelly ' +
  'sells weigh dearest fatal fighters harsh hysterical inspiration medium situations submarine bam compound haul meters ridge ' +
  'strain buys cooler expose gag herd lifted sector caring feds nowadays objective pursuit sentimental tales compromise ' +
  'congratulate cord experiences guardian length mule narrow smashed sting strict beautifully closes fax lonesome plead resting ' +
  'smoked automatic controlled cries grunts lands officials relaxed shoots tobacco intimate nun originally satisfaction shelf stepping ' +
  'subjects wires blaming emotionally grease hobby household moonlight semester stud subtle tolerate volume voted cleaner compliments ' +
  'convincing geek knives commanding crab elements explaining fountain myth opposed pervert resort servants speaker bolt currently ' +
  'domestic gravity label pledge razor teenager chow clamp clearance dispatch eager eighth electronic faggot messy slick ' +
  'sorrow teenage visited bean collecting complaints maintenance mug plea restaurants shovel attraction avoiding coordinates hardware races ' +
  'conscious jackass pose sensible blocked colleague experts nickname slightest sophisticated touches troubled affected anxiety classified dudes ' +
  'loop wakes lottery med obligation painter psych remaining spreading theft driveway items proposed psychological referring traveled ' +
  'confidential feast hardest logic negotiate online pirates preacher rabbi rarely sponge strongly swallowed baked detectives locks ' +
  'lodge scissors accidents bonds cigars circuit drivers finals leap possessed respects targets brakes dreamt enforcement galaxy ' +
  'guaranteed humiliated proven threats urge wishing disagree disk dot element endless feather greedy inappropriate responsibilities vegetables ' +
  'bicycle democracy frequency funds jeans mattress melody memo rejected tubes withdraw catches copper innocence notion offices ' +
  'promising respected warriors coal dragging experiments mice amateur architect consideration gown internet marching miracles ninth pier ' +
  'pregnancy salmon siren starboard carries charts declared detention engineering gasoline hike registration survivors beep cancelled colleagues ' +
  'doubts risks urine vain airline approved clearing explosives forgiven kidnap laboratory morphine pronounce rehab riot robbing ' +
  'significant vows choke granddaughter involve lined methods wardrobe beeping cheerleader growth mansion mustard naive phoned fart ' +
  'happiest rabbits ram stew altogether click creeps discharge drift extend ginger offensive pursue quest reservations tearing ' +
  'whereabouts canal carrier cups customs hangs healing literature persuade psychotic tech earthquake hay hereby initial performing ' +
  'purchase regulations roots tribe backing bein cereal chap convict depressing frighten intact peach shares spilled surf ' +
  'wealth bake breed companion counted establish lighting lions nursing outrageous pond underwater winners absence footsteps hairy ' +
  'settlement shipment shipping stripes tasty crashing curtains deceased diving global prophecy worms bunk charging clues elegant ' +
  'faced lease liking spark syndrome velvet authorized bourbon compassion deliberately ignorant puke scenario serves timer baggage ' +
  'coverage define figuring overtime retarded scrub sperm straw ashore bluff brat breach cavalry clowns erase explore ' +
  'meter replacement treats alcoholic assured bedtime crib custom horns mines overcome pine smiles stain struggling unnecessary ' +
  'wheelchair accountant camping civilized dental distinguished drunken elsewhere est hospitals hottest lasted shocking applied definite engage ' +
  'fare pudding starve acknowledge booty earrings elbow entertain essay physician platform represents scam swinging yelled abilities ' +
  'den habits heavily ironic pinch products rendezvous stadium bathtub cloth debts investigator journalist lawsuit stack unpleasant ' +
  'vast bumped chorus contain creation fiction invention isolated ketchup positively pounding antique bats comb correctly hips ' +
  'noodles protective sunrise articles bribe cured dash directed encourage musician ahold luxury rushing surprising waits civilians ' +
  'depending exotic furious garlic insulted niggers passionate principles printed vehicles voyage brake bubbles differences eliminate generations ' +
  'poster sincere steer trading compartment confessed costumes graves scent shade stereo supervisor boil conviction cracking parlor ' +
  'peak ropes shook slipping writers assassin colony dances flashlight poisoning pouring slack spaghetti stamp wit wolves ' +
  'groceries handwriting holler ignored lighten mortgage murderers nude organs pigeon regrets reliable rib shallow skate stir ' +
  'tomato additional ammunition biological coats courts cycle destination glue harassment humiliating hunger inspection modest pals shorter ' +
  'sloppy deadline despair probation sofa tequila universal wander accomplish battalion divide documentary fastest feature housekeeper poke ' +
  'recognise revealed shaving spends desperately fuzzy muffin pajamas pressed sour whales whores wonders chambers contracts definition ' +
  'economy martial queer slam troop vet busting directors hilarious neighbourhood obliged presented remembering spells streak sweetest ' +
  'tow cheque classy cracker disco frightening tab trusting vacuum variety blocking collected consistent dam facial glow ' +
  'jealousy occupied orphan questioned resent roller scored spine suing tasted wheat appreciated bodyguard butts janitor naval ' +
  'owners prettiest sticky automobile cakes chemicals cuff era exposure feathers flood handful medic millionaire nicest towns ' +
  'vegetable witnessed accuse attract clip crooked database generator mentally pets resume tails tease toad announced cafeteria ' +
  'collapsed crackers craft crook dolls expedition feared intel interrogation lethal masks obsession onions pressing scoop spectacular ' +
  'cozy delight entertaining inevitable orbit respectable seeking shack travels ultimately adjust blamed chauffeur essence farther fireworks ' +
  'preserve suction tomb developing doom evacuate fade intent oak owl promoted quarrel relevant satisfy scope sleeve ' +
  'consult conversations difficulty felony fitting homecoming knots poop presidential projects rubbish speeches audio corridor defeated dove ' +
  'encounter framed heartbeat listed lust programs relieve shells taller trainer vest collapse execute foreman gorilla issued ' +
  'misunderstood rodeo stressed transportation vanished burglar concentration educated freeway ghetto grid heavenly identical loosen maiden moose ' +
  'profits punched shuttle strawberry submit veins assassination bloom butterfly chewing examination lemonade orchestra prey ruled sane ' +
  'tactical artillery bark bites channels confirmation dozens grocery possess sew slot unlock weep whispers allows ancestors ' +
  'barber dismiss hesitate hiring listens psychology puppet runway scouts sidewalk spying squirrel statements waltz bananas defensive ' +
  'importantly puppies reader slaughter ambush anyplace chops disappointment indicates mint politicians portrait rang choosing deserted forcing ' +
  'hatred rescued suggestions theories tougher tourists vengeance vow behaviour clumsy corners departure digital examined extension fag ' +
  'failing pause perfection popping towers ammo bands bin delayed employer equally hideous insulting mock tango thankful ' +
  'acquaintance addict ambition ant donkey ethics ferry finance mouths offence orphanage peel rebel requests sponsor bees ' +
  'blouse crank dancers employment evolution gangster graveyard kneel landlord peek recommended specialty stray vomit wrecked artery ' +
  'choir corrupt explosive flirting headaches jurisdiction marijuana topic unacceptable appointed cottage dealers diapers dose partnership repeating ' +
  'representative spice acceptable bruises gravy historical humour impulse includes madman pains pearls stalking denial expectations greet ' +
  'interviews kung lone measures produced rushed sole advised carbon designer devils disrespect gutter interior interrupted marker ' +
  'que reaches realised stamps stripper text tribute arrogant cuffs globe goofy gunfire heir marble offend rains ' +
  'vibe waving allowance boogie hairs junkie leaf precise repay residents teaches bulls buyer fracture fugitive gained ' +
  'shifts slower specialist untie videotape banquet caution condom freezer handcuffs hunk mode needles override primitive rep ' +
  'saves slippers strap thread trousers tumor valet virtue volunteers fragile goals hanged instruments irrelevant narcotics panicked ' +
  'purposes regardless saloon secured sensors smokes sobbing supposedly waist amazed appreciation backstage detect drip fails hog ' +
  'juvenile majority rifles skeleton whistling allies assets battles blankets choking contains immortal motto playground procedures publish ' +
  'secretly sip syrup transplant unstable altar amigo boyfriends fireplace funky grunting lyrics overboard premises treason ads ' +
  'blink cafe dried mechanic purely recommendation regards reserved ribbon skipped underestimate unlikely vagina bluffing buckle flick ' +
  'gladly hotels hound noisy payroll pneumonia resign stash traces utter camel cocoa condoms contempt diplomatic justify ' +
  'legacy mainly opinions rational reconsider reflection region salvation spelling suggests abducted burgers climbed fantasies flavor frustrated ' +
  'involves loneliness paramedics stitches supermarket toothbrush youngest belts conquer pissing plasma speeding static stoned torch desires ' +
  'economic efficient ensure flipped jumps par patterns restore runner slapped slug smelling visible accusing chronic hath ' +
  'lasts lifestyle mustache quiz recorder rookie shakes sinking sketch update artistic careless cheaper compromised coughing cracks ' +
  'dagger humming licence lid maker maps overwhelming qualities reckless skating smiled snapped suckers tricked abroad adjourned ' +
  'allowing associates biology biting blunt bridges childish concerning disposal mechanical rebels strangled toxic tracked weasel ' +
  '').trim().split(' ');
