(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='keygrove.v2';
const LESSONS=[
{id:'home',title:'Home Row',keys:'asdfjkl;',copy:'Find the resting keys and build a calm rhythm.',texts:['asdf jkl; asdf jkl;','sad lad; fall ask;','a flask; a sad fall;']},
{id:'reach',title:'Home Reach',keys:'gh',copy:'Add the center reach without losing your anchor.',texts:['dash flag; glass hall','flash; glad; half;','a glad lass had salad']},
{id:'top',title:'Top Row',keys:'qwertyuiop',copy:'Climb to the top row and return home cleanly.',texts:['type your quiet power','we write pretty poetry','quiet typewriter power']},
{id:'bottom',title:'Bottom Row',keys:'zxcvbnm,.',copy:'Drop to the lower row with light reaches.',texts:['calm hands move below.','mix calm moves, then zoom.','a brave fox can move.']},
{id:'words',title:'Word Path',keys:'abcdefghijklmnopqrstuvwxyz',copy:'Mix rows into useful words and phrases.',texts:['steady hands make clear words','small habits build quiet speed','accuracy grows before speed']},
{id:'notes',title:'Delivered Notes',keys:'abcdefghijklmnopqrstuvwxyz,.;',copy:'Finish with natural sentences and punctuation.',texts:['Take the long path home, and keep a gentle pace.','Small, accurate steps turn into useful speed.','Good typing feels quiet before it feels fast.']}
];
const CHARMS=[['*','First Leaf',s=>s.stats.runs>=1],['+','True Note',s=>s.stats.bestAcc>=95],['>','Quick Finch',s=>s.stats.bestWpm>=30],['=','Three Pines',s=>s.completed.length>=3],['#','Trail Map',s=>s.completed.length===LESSONS.length]];
const fresh=()=>({selected:'home',completed:[],stats:{runs:0,chars:0,attempts:0,bestWpm:0,bestAcc:0}});
function clean(x){let s=fresh();if(!x||typeof x!=='object')return s;s.selected=LESSONS.some(l=>l.id===x.selected)?x.selected:'home';s.completed=Array.isArray(x.completed)?[...new Set(x.completed.filter(id=>LESSONS.some(l=>l.id===id)))]:[];let q=x.stats||{};for(let k of Object.keys(s.stats))s.stats[k]=Math.max(0,Number(q[k])||0);return s}
function load(){try{return clean(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return fresh()}}
let state=load(),run=null,timer=null;
const lesson=()=>LESSONS.find(l=>l.id===state.selected)||LESSONS[0],idx=()=>Math.max(0,LESSONS.findIndex(l=>l.id===state.selected));
const unlocked=i=>i===0||state.completed.includes(LESSONS[i-1].id);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function html(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function charms(){return CHARMS.filter(c=>c[2](state))}
function profile(){$('sideWpm').textContent=Math.round(state.stats.bestWpm);$('sideRuns').textContent=state.stats.runs;$('sideCharms').textContent=`${charms().length}/${CHARMS.length}`;$('progressPill').textContent=state.completed.length===LESSONS.length?'Trail complete':`Lesson ${Math.min(LESSONS.length,state.completed.length+1)} of ${LESSONS.length}`}
function trail(){let g=$('trailGrid');g.innerHTML='';LESSONS.forEach((l,i)=>{let open=unlocked(i),done=state.completed.includes(l.id),a=document.createElement('article');a.className='lesson'+(open?'':' locked');a.innerHTML=`<div class="row"><span class="pill">${i+1}</span><span class="done">${done?'Complete':open?'Open':'Locked'}</span></div><h3>${l.title}</h3><p>${l.copy}</p><div class="keys">${[...new Set(l.keys)].map(k=>`<span>${html(k)}</span>`).join('')}</div><footer><span class="done">${done?'Ready to revisit':'Accuracy before speed'}</span><button class="go" ${open?'':'disabled'} data-id="${l.id}">${done?'Practice':'Start'}</button></footer>`;g.appendChild(a)});g.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.id;save();reset();show('practice')})}
function pick(){let l=lesson();return l.texts[Math.floor(Math.random()*l.texts.length)]}
function reset(){run={text:pick(),pos:0,status:'idle',hits:0,attempts:0,errors:0,start:0,wrong:false};$('capture').value='';practice()}
function prompt(){let p=$('prompt');p.innerHTML='';[...run.text].forEach((c,i)=>{let s=document.createElement('span');s.textContent=c;s.className='ch'+(i<run.pos?' done':'')+(i===run.pos?' current':'')+(i===run.pos&&run.wrong?' wrong':'');p.appendChild(s)})}
function metrics(){let min=run.start?Math.max(.01,(performance.now()-run.start)/60000):0,w=min?Math.round((run.hits/5)/min):0,a=run.attempts?Math.round(run.hits/run.attempts*100):100,p=Math.round(run.pos/run.text.length*100);$('wpm').textContent=w;$('acc').textContent=a+'%';$('pct').textContent=p+'%';return{w,a,p}}
function keyboard(){let hot=new Set(lesson().keys),rows=['qwertyuiop','asdfghjkl;','zxcvbnm,.'];$('keyboard').innerHTML=rows.map(r=>`<div class="keyrow">${[...r].map(k=>`<span class="key${hot.has(k)?' hot':''}">${html(k)}</span>`).join('')}</div>`).join('')}
function renderCharms(){let on=new Set(charms().map(c=>c[1]));$('charms').innerHTML=CHARMS.map(c=>`<div class="charm${on.has(c[1])?' on':''}"><div><b>${c[0]}</b>${c[1]}</div></div>`).join('')}
function practice(){let l=lesson();$('lessonTitle').textContent=l.title;$('lessonMeta').textContent='Keys: '+[...l.keys].join(' ');prompt();metrics();keyboard();renderCharms();$('startBtn').textContent=run.status==='playing'?'Typing...':'Start typing';$('hint').textContent=run.status==='playing'?'Keep your eyes on the highlighted character.':'Start, then type the highlighted character.'}
function start(){if(run.status==='complete')reset();run.status='playing';run.pos=run.hits=run.attempts=run.errors=0;run.wrong=false;run.start=performance.now();practice();$('capture').focus()}
function type(k){if(run.status!=='playing'||k.length!==1)return;let want=run.text[run.pos],ok=k===want;run.attempts++;if(ok){run.hits++;run.pos++;run.wrong=false;if(run.pos===run.text.length)return finish()}else{run.errors++;run.wrong=true}prompt();metrics()}
function finish(){run.status='complete';let m=metrics();state.stats.runs++;state.stats.chars+=run.hits;state.stats.attempts+=run.attempts;state.stats.bestWpm=Math.max(state.stats.bestWpm,m.w);state.stats.bestAcc=Math.max(state.stats.bestAcc,m.a);if(m.a>=80&&!state.completed.includes(state.selected)){state.completed.push(state.selected);let i=idx();if(i<LESSONS.length-1)toast(LESSONS[i+1].title+' unlocked.')}save();render();$('resultWpm').textContent=m.w;$('resultAcc').textContent=m.a+'%';$('resultErrors').textContent=run.errors;$('resultText').textContent=m.a>=95?'Precise and steady.':m.a>=85?'A solid run. Keep accuracy in front.':'Slow down slightly and let accuracy lead.';open('resultModal')}
function growth(){let life=state.stats.attempts?Math.round(state.stats.chars/state.stats.attempts*100):100,vals=[['Best WPM',Math.round(state.stats.bestWpm)],['Best accuracy',Math.round(state.stats.bestAcc||100)+'%'],['Notes delivered',state.stats.runs],['Lifetime accuracy',life+'%']];$('growth').innerHTML=vals.map(v=>`<div class="stat"><small>${v[0]}</small><b>${v[1]}</b></div>`).join('')}
const copy={trail:['Your path','A quieter way to get faster.','Move through short lessons, keep accuracy ahead of speed, and collect small charms as the trail opens.'],practice:['Typing desk','One clean key at a time.','Use the highlighted character as your only target. Speed follows once the motion feels easy.'],growth:['Local journal','Progress you can actually see.','Completed-run stats stay in this browser unless you export a backup.']};
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));[$('eyebrow').textContent,$('title').textContent,$('lede').textContent]=copy[v];if(v==='practice')setTimeout(()=>$('capture').focus(),0);if(v==='growth')growth()}
function render(){profile();trail();practice();growth()}
function open(id){$(id).classList.add('open')}function close(id){$(id).classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
$('settingsBtn').onclick=()=>open('settingsModal');$('startBtn').onclick=start;$('newBtn').onclick=()=>{reset();$('capture').focus()};$('capture').onkeydown=e=>{if(run.status==='playing'){e.preventDefault();type(e.key)}};document.onkeydown=e=>{if(run.status==='playing'&&!document.querySelector('.modal.open')&&document.activeElement!==$('capture')&&e.key.length===1){e.preventDefault();type(e.key)}};
$('againBtn').onclick=()=>{close('resultModal');reset();start()};$('trailBtn').onclick=()=>{close('resultModal');show('trail')};
$('exportBtn').onclick=()=>{save();let u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='keygrove-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;state=clean(JSON.parse(await f.text()));save();reset();render();close('settingsModal');toast('Progress restored.')}catch{toast('That backup could not be read.')}e.target.value=''};$('resetBtn').onclick=()=>{if(confirm('Reset Keygrove progress?')){state=fresh();save();reset();render();close('settingsModal');show('trail')}};
setInterval(()=>{if(run?.status==='playing')metrics()},500);reset();render();show('trail');save();Object.defineProperty(window,'keygrove',{value:Object.freeze({snapshot:()=>JSON.parse(JSON.stringify({state,run})),lessons:()=>LESSONS.map(x=>({...x}))})});
})();
