#!/usr/bin/env python3
"""Export the v1 movement vocabulary into the app (src/curriculum/movements.ts).

Reads outputs/candidates/*.csv (RES-03) and writes only the v1 cut fixed by
docs/04-movement-vocabulary-checkpoint.md and the spec scaffold (H2–H4):

  TECHNICAL_TRANSITIONS  the 11 targets  ed de ce ec tr un lo ol rt mu um
  CHUNKS                 ing ion tion nce ted
  PRACTICE_WORDS         everyday carrier words for those 16 targets
  COMMON_TRANSITIONS     the universal bigrams (top-200 in all three corpora),
                         then the rest with a smallest share >= 0.01%, flagged —
                         each new-key lesson's headline movement when no
                         technical target applies (v1.1)
  EVERYDAY_WORDS         outputs/candidates/everyday_words.csv, most frequent
                         first — the vocabulary that carries a movement into
                         words (v1.1)

Everything else in the CSVs stays provisional and is deliberately not
exported. Run `make export`; the generated file must not be edited by hand.
"""

from __future__ import annotations

import csv
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAND = ROOT / "outputs" / "candidates"
TABLES = ROOT / "outputs" / "tables"
APP = ROOT.parents[1]
OUT = APP / "src" / "curriculum" / "movements.ts"

VERSION = "1.1"
TARGETS = ["ed", "de", "ce", "ec", "tr", "un", "lo", "ol", "rt", "mu", "um"]
CHUNKS = ["ing", "ion", "tion", "nce", "ted"]


def rows(name: str) -> list[dict]:
    with (CAND / name).open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(line for line in f if not line.startswith("#")))


def source_commit() -> str:
    out = subprocess.run(
        ["git", "log", "-1", "--format=%h", "--", str(CAND), str(TABLES / "bigrams_cross_corpus.csv")],
        cwd=APP, capture_output=True, text=True,
    )
    return out.stdout.strip() or "uncommitted"


technical = {r["bigram"]: r for r in rows("technical_transitions.csv")}
gestures = {r["gesture"]: r for r in rows("gestures.csv")}
words: dict[str, list[str]] = {}
for r in rows("practice_words.csv"):
    words.setdefault(r["target"], []).append(r["word"])

with (TABLES / "bigrams_cross_corpus.csv").open(newline="", encoding="utf-8") as f:
    table = list(csv.DictReader(f))
MIN_FALLBACK_SHARE = 0.0001
common_share = {r["ngram"]: min(float(r[f"share_{c}"] or 0) for c in ("books", "web", "subtlex")) for r in table}
universal = {r["ngram"] for r in table if r["stability_class"] == "universal"}
common_order = sorted((g for g in common_share if g in universal or common_share[g] >= MIN_FALLBACK_SHARE),
                      key=lambda g: (g not in universal, -common_share[g], g))
# SUBTLEX splits contractions ("you're" -> "you" + "re"); drop the stranded fragments, keep "a" and "i".
CONTRACTION_FRAGMENTS = {"re", "s", "t", "m", "d"}
# Two-letter entries past the most frequent 100 are interjections, abbreviations and fragments (uh, ls, nd, rd); drop them.
TWO_LETTER_RANK = 100
everyday = [r["word"] for r in rows("everyday_words.csv") if r["word"] not in CONTRACTION_FRAGMENTS]
everyday = [w for i, w in enumerate(everyday) if len(w) > 2 or w in ("a", "i") or (len(w) == 2 and i < TWO_LETTER_RANK)]

missing = [t for t in TARGETS if t not in technical] + [c for c in CHUNKS if c not in gestures]
if missing:
    raise SystemExit(f"v1 targets missing from candidates: {missing}")


def ts_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


L: list[str] = []
add = L.append
add("// GENERATED by research/typing-movements/scripts/export_movements.py — do not edit.")
add(f"// Source: outputs/candidates/*.csv and outputs/tables/bigrams_cross_corpus.csv at commit {source_commit()} (RES-01/RES-03); v1 cut per docs/04-movement-vocabulary-checkpoint.md.")
add("// Provisional until learner data (DEC-16). Regenerate with `make export` in research/typing-movements.")
add("import type { Chunk, TechnicalTransition } from './types';")
add("")
add(f"export const MOVEMENT_VOCABULARY_VERSION = {ts_str(VERSION)};")
add("")
add("/** The 11 same-finger targets that get isolated practice in v1 (scaffold C3). */")
add("export const TECHNICAL_TRANSITIONS: readonly TechnicalTransition[] = [")
for t in TARGETS:
    r = technical[t]
    add(
        f"  {{ bigram: {ts_str(t)}, minShare: {float(r['min_share']):.5f}, stability: {ts_str(r['stability'])}, "
        f"classByMethod: {{ 'traditional@1.0': {ts_str(r['movement_class'])}, 'relaxed-qwerty@1.0': {ts_str(r['relaxed_class'])} }}, "
        f"sameFingerTravel: {float(r['same_finger_travel']) if r['same_finger_travel'] else 0:.2f} }},"
    )
add("];")
add("")
add("/** Common chunks practised only inside words in v1 (scaffold C4). */")
add("export const CHUNKS: readonly Chunk[] = [")
for c in CHUNKS:
    r = gestures[c]
    feats = [f for f in r["features"].split(";") if f]
    add(
        f"  {{ ngram: {ts_str(c)}, minShare: {float(r['min_share']):.5f}, stability: {ts_str(r['stability'])}, "
        f"features: [{', '.join(ts_str(f) for f in feats)}] }},"
    )
add("];")
add("")
add("/** Everyday carrier words per target, short carriers first (research practice-word set). */")
add("export const PRACTICE_WORDS: Readonly<Record<string, readonly string[]>> = {")
for t in TARGETS + CHUNKS:
    add(f"  {t}: [{', '.join(ts_str(w) for w in words.get(t, []))}],")
add("};")
add("")
add("/** Letter bigrams by their smallest share across books, web and subtitles: the universal ones (top-200 in all three) first,")
add(" * then the rest at >= 0.01%, each flagged. A new-key lesson with no technical target takes its headline movement from here")
add(" * (CURR-50). Coverage data, not a difficulty score (DEC-16). */")
add("export const COMMON_TRANSITIONS: readonly { bigram: string; minShare: number; universal: boolean }[] = [")
for g in common_order:
    add(f"  {{ bigram: {ts_str(g)}, minShare: {common_share[g]:.5f}, universal: {'true' if g in universal else 'false'} }},")
add("];")
add("")
add("/** Everyday words (SUBTLEX-US frequent, in many films, mostly lower-case, in the Google Books list, not excluded), most")
add(" * frequent first — the research practice-word filter applied to the whole vocabulary. */")
add("export const EVERYDAY_WORDS: readonly string[] = (")
for i in range(0, len(everyday), 16):
    add(f"  {ts_str(' '.join(everyday[i:i + 16]) + ' ')} +")
add("  '').trim().split(' ');")
add("")

OUT.write_bytes("\n".join(L).encode("utf-8"))  # LF on every OS, matching the repo
print(f"Wrote {OUT.relative_to(APP)} ({OUT.stat().st_size} bytes)")
