#!/usr/bin/env python3
"""Export the v1 movement vocabulary into the app (src/curriculum/movements.ts).

Reads outputs/candidates/*.csv (RES-03) and writes only the v1 cut fixed by
docs/04-movement-vocabulary-checkpoint.md and the spec scaffold (H2–H4):

  TECHNICAL_TRANSITIONS  the 11 targets  ed de ce ec tr un lo ol rt mu um
  CHUNKS                 ing ion tion nce ted
  PRACTICE_WORDS         everyday carrier words for those 16 targets

Everything else in the CSVs stays provisional and is deliberately not
exported. Run `make export`; the generated file must not be edited by hand.
"""

from __future__ import annotations

import csv
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAND = ROOT / "outputs" / "candidates"
APP = ROOT.parents[1]
OUT = APP / "src" / "curriculum" / "movements.ts"

VERSION = "1.0"
TARGETS = ["ed", "de", "ce", "ec", "tr", "un", "lo", "ol", "rt", "mu", "um"]
CHUNKS = ["ing", "ion", "tion", "nce", "ted"]


def rows(name: str) -> list[dict]:
    with (CAND / name).open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(line for line in f if not line.startswith("#")))


def source_commit() -> str:
    out = subprocess.run(
        ["git", "log", "-1", "--format=%h", "--", str(CAND)],
        cwd=APP, capture_output=True, text=True,
    )
    return out.stdout.strip() or "uncommitted"


technical = {r["bigram"]: r for r in rows("technical_transitions.csv")}
gestures = {r["gesture"]: r for r in rows("gestures.csv")}
words: dict[str, list[str]] = {}
for r in rows("practice_words.csv"):
    words.setdefault(r["target"], []).append(r["word"])

missing = [t for t in TARGETS if t not in technical] + [c for c in CHUNKS if c not in gestures]
if missing:
    raise SystemExit(f"v1 targets missing from candidates: {missing}")


def ts_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


L: list[str] = []
add = L.append
add("// GENERATED by research/typing-movements/scripts/export_movements.py — do not edit.")
add(f"// Source: outputs/candidates/*.csv at commit {source_commit()} (RES-03); v1 cut per docs/04-movement-vocabulary-checkpoint.md.")
add("// Provisional until learner data (DEC-16). Regenerate with `make export` in research/typing-movements.")
add("import type { Chunk, TechnicalTransition } from './types';")
add("")
add(f"export const MOVEMENT_VOCABULARY_VERSION = {ts_str(VERSION)};")
add("")
add("/** The 11 same-finger targets that get isolated practice in v1 (scaffold C3). */")
add("export const TECHNICAL_TRANSITIONS: readonly TechnicalTransition[] = [")
for t in TARGETS:
    r = technical[t]
    add(
        f"  {{ bigram: {ts_str(t)}, minShare: {float(r['min_share']):.5f}, stability: {ts_str(r['stability'])}, "
        f"classByMethod: {{ 'traditional@1.0': {ts_str(r['movement_class'])}, 'relaxed-qwerty@1.0': {ts_str(r['relaxed_class'])} }}, "
        f"sameFingerTravel: {float(r['same_finger_travel']) if r['same_finger_travel'] else 0:.2f} }},"
    )
add("];")
add("")
add("/** Common chunks practised only inside words in v1 (scaffold C4). */")
add("export const CHUNKS: readonly Chunk[] = [")
for c in CHUNKS:
    r = gestures[c]
    feats = [f for f in r["features"].split(";") if f]
    add(
        f"  {{ ngram: {ts_str(c)}, minShare: {float(r['min_share']):.5f}, stability: {ts_str(r['stability'])}, "
        f"features: [{', '.join(ts_str(f) for f in feats)}] }},"
    )
add("];")
add("")
add("/** Everyday carrier words per target, short carriers first (research practice-word set). */")
add("export const PRACTICE_WORDS: Readonly<Record<string, readonly string[]>> = {")
for t in TARGETS + CHUNKS:
    add(f"  {t}: [{', '.join(ts_str(w) for w in words.get(t, []))}],")
add("};")
add("")

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"Wrote {OUT.relative_to(APP)} ({OUT.stat().st_size} bytes)")
